### ISSUE TITLE
error on the first run

### ISSUE THREAD

**Issue by clonq** [apideck-libraries/portman#99]
Hi there,

I'm getting an ```UnhandledPromiseRejectionWarning: TypeError: tslib_1.__spreadArray is not a function``` error after the ```Conversion successful``` message when I run ```portman --cliOptionsFile portman/portman-cli.json``` on a basic openapi spec file with the default portman-cli.json generated by ```portman --init```

Any hints?

**Comment by thim81** [comment]
@clonq Could you share the cli config file? That way we can try to reproduce the error.

**Comment by clonq** [comment]
{
  "local": "test/api.spec.yml",
  "output": "test/api.postman.json",
  "envFile": "portman/.env-portman",
  "includeTests": true,
  "syncPostman": false,
  "runNewman": false
}

**Comment by thim81** [comment]
@clonq We tried to reproduce the error, but we were unable to reproduce it with the following config

```
{
  "local": "./tmp/crm.openapi.yml",
  "output": "./tmp/api.postman.json",
  "envFile": "portman/.env-portman",
  "includeTests": true,
  "syncPostman": false,
  "runNewman": false
}
```

Where `crm.openapi.yml` contains the OpenAPI as defined to https://github.com/apideck-libraries/portman/blob/main/examples/cli-options/crm.openapi.yml

Could you check a couple of thing for us:
- Bump your packages.json to use the latest version: 1.4.2 
```
  "dependencies": {
    "@apideck/portman": "^1.4.2",
```

- If the provided OpenAPI is valid? You can use a online service for this: https://apitools.dev/swagger-parser/online/

If the issue still remains after the above checks, would you be able to the share the OpenAPI spec with us, so we can try to reproduce the behaviour locally?

**Comment by clonq** [comment]
Same error after upgrading to 1.4.2 and using the sample crm file. The error seems to be in injectEnvVariables judging by the stack trace. And my .env-portman file is empty.

**Comment by thim81** [comment]
@clonq Could you share the stack trace? Since we seems to be unable to reproduce it.

**Comment by clonq** [comment]
(node:71950) UnhandledPromiseRejectionWarning: TypeError: tslib_1.__spreadArray is not a function
    at Object.injectEnvVariables (testprj/node_modules/@apideck/portman/dist/application/globals/injectEnvVariables.js:46:28)
    at CollectionWriter.execute (testprj/node_modules/@apideck/portman/dist/application/CollectionWriter.js:25:29)
    at Portman.<anonymous> (testprj/node_modules/@apideck/portman/dist/Portman.js:297:34)
    at step (testprj/node_modules/tslib/tslib.js:140:27)
    at Object.next (testprj/node_modules/tslib/tslib.js:121:57)
    at testprj/node_modules/tslib/tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (testprj/node_modules/tslib/tslib.js:110:16)
    at Portman.runPortmanOverrides (testprj/node_modules/@apideck/portman/dist/Portman.js:292:24)
    at Portman.<anonymous> (testprj/node_modules/@apideck/portman/dist/Portman.js:252:45)
    at step (testprj/node_modules/tslib/tslib.js:140:27)
    at Object.next (testprj/node_modules/tslib/tslib.js:121:57)
    at fulfilled (testprj/node_modules/tslib/tslib.js:111:62)

**Comment by thim81** [comment]
@clonq In the 1.5.0 release of Portman, it should be fixed.

The cause was that "spreadArray is not a function" since the _spreadArrays function for TypeScript has been deprecated.

If it is not fixed, feel free to reopen this item or create a new one.

**Comment by clonq** [comment]
Stacktrace after upgrading to 1.5.0:

(node:18695) UnhandledPromiseRejectionWarning: TypeError: tslib_1.__spreadArray is not a function
    at Object.writeCollectionPreRequestScripts (testprj/node_modules/@apideck/portman/dist/application/globals/writeCollectionPreRequestScripts.js:19:75)
    at CollectionWriter.execute (testprj/node_modules/@apideck/portman/dist/application/CollectionWriter.js:34:29)
    at Portman.<anonymous> (testprj/node_modules/@apideck/portman/dist/Portman.js:303:34)
    at step (testprj/node_modules/tslib/tslib.js:140:27)
    at Object.next (testprj/node_modules/tslib/tslib.js:121:57)
    at testprj/node_modules/tslib/tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (testprj/node_modules/tslib/tslib.js:110:16)
    at Portman.runPortmanOverrides (testprj/node_modules/@apideck/portman/dist/Portman.js:298:24)
    at Portman.<anonymous> (testprj/node_modules/@apideck/portman/dist/Portman.js:254:45)
    at step (testprj/node_modules/tslib/tslib.js:140:27)
    at Object.next (testprj/node_modules/tslib/tslib.js:121:57)
    at fulfilled (testprj/node_modules/tslib/tslib.js:111:62)

**Comment by thim81** [comment]
@clonq In PR #110, we aim to replace all spread array implementations with a compatible implementation.

After the review, it will be included in an upcoming release and should fix your errors.

**Comment by thim81** [comment]
@clonq The changes have been merged into the 1.5.1 release. 

I'm going to leave this item open, and hope you can validate if the 1.5.1 release have fixed this unwanted error.
If the error is solved, would you be so kind to close the item.
If the error remains, could you let us know the error stack trace and share any additional info that could help us to reproduce the problem.

**Comment by clonq** [comment]
Looks like it works. Thanks guys.
